title = "Ernest Dong"
baseURL = "https://ernestdong.github.io"
theme = "cactus" #"researcher"
enableEmoji = true
hasCJKLanguage = true
[params]
  description = "A Sisyphus Rolling Up Rock"
  favicon = "/images/favicon.ico"
  showAllPostsOnHomePage = true
  postsOnHomePage = 5
  mainSection = "notes"
  mainSectionTitle = "Thesis Notes"
  tocInline = false
  showReadTime = true
  mathjax = true
  css = ["css/custom.css"]
  [[params.social]]
    name = "fab fa-github"
    link = "https://github.com/ernestDong/"
  [[params.social]]
    name = "fab fa-linkedin-in"
    link = "https://www.linkedin.com/in/晨阳-董-918ab41b4/"
  [[params.social]]
    name = "fab fa-instagram"
    link = "https://www.instagram.com/ernestdong2000/"
  [[params.social]]
    name = "email"
    link = "dongcy2000@outlook.com"
[menu]
  [[menu.main]]
    name = "Home"
    url = "/"
    weight = 1
  [[menu.main]]
    name = "Notes"
    url = "/notes"
    weight = 2
  [[menu.main]]
    name = "Posts"
    url = "/posts"
    weight = 3
  [[menu.main]]
    name = "Tags"
    url = "/tags"
    weight = 4
  [[menu.main]]
    name = "About"
    url = "/readme/index.html"
    weight = 5
  [[menu.main]]
    name = "Resume"
    url = "/files/resume.pdf"
    weight = 5
[markup]
  [markup.highlight]
    codeFences = true
    guessSyntax = true
    hl_Lines = ""
    lineNoStart = 1
    lineNos = true
    lineNumbersInTable = true
    noClasses = true
    style = "dracula"
    tabWidth = 4
  [markup.goldmark.renderer]
    unsafe= true
  [markup.tableOfContents]
    endLevel = 3
    ordered = false
    startLevel = 2
